# Generated by Django 5.1.7 on 2025-08-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionrecord',
            name='collected_image',
        ),
        migrations.RemoveField(
            model_name='trashsubmission',
            name='image',
        ),
    ]
