# Generated by Django 5.1.7 on 2025-08-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0002_remove_collectionrecord_collected_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashsubmission',
            name='trash_description',
        ),
    ]
