# Generated by Django 5.1.7 on 2025-08-25 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0003_remove_trashsubmission_trash_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_amount', models.PositiveIntegerField(verbose_name='Points to Claim')),
                ('claim_type', models.CharField(choices=[('payment', 'Payment'), ('donation', 'Donation')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'In Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('processed_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_claims', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
