# Generated by Django 5.1.7 on 2025-08-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0004_rewardclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardclaim',
            name='donation_hospital',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Donation Hospital'),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='monetary_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monetary Amount (Rs)'),
        ),
    ]
