# Generated by Django 5.2.5 on 2025-09-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0006_alter_collectionrecord_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashsubmission',
            name='actual_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Actual Weight (kg)'),
        ),
        migrations.AddField(
            model_name='trashsubmission',
            name='weight_notes',
            field=models.TextField(blank=True, verbose_name='Weight Notes'),
        ),
        migrations.AddField(
            model_name='trashsubmission',
            name='weight_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
