# Generated by Django 5.2.5 on 2025-09-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0007_trashsubmission_actual_weight_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashsubmission',
            name='actual_weight_kg',
        ),
        migrations.RemoveField(
            model_name='trashsubmission',
            name='weight_notes',
        ),
        migrations.RemoveField(
            model_name='trashsubmission',
            name='weight_updated_at',
        ),
        migrations.AlterField(
            model_name='trashsubmission',
            name='rider_notes',
            field=models.TextField(blank=True, null=True, verbose_name="Rider's Notes"),
        ),
    ]
