# Generated by Django 5.1.7 on 2025-08-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Recycle Bin', max_length=100)),
                ('site_description', models.TextField(default='Transform waste into rewards with our eco-friendly recycling platform')),
                ('contact_email', models.EmailField(default='admin@trashtotreasure.com', max_length=254)),
                ('default_timezone', models.CharField(default='UTC', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='System is currently under maintenance. Please check back later.')),
                ('debug_mode', models.BooleanField(default=False)),
                ('log_level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], default='INFO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
