# Generated by Django 5.2.5 on 2025-09-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_systemsettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='co2_reduction_tons',
            field=models.IntegerField(default=15, help_text='CO2 reduction in tons annually'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='landfill_space_acres',
            field=models.IntegerField(default=10, help_text='Landfill space saved in acres'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='trees_saved_count',
            field=models.IntegerField(default=500, help_text='Number of trees saved'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='water_saved_gallons',
            field=models.IntegerField(default=1000, help_text='Water saved in gallons'),
        ),
    ]
