# Generated by Django 5.2.5 on 2025-09-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, help_text='Default collection location', max_length=255),
        ),
    ]
